### PR TITLE
Gitignore lock file

### PR DESCRIPTION
**Pull request by victor0801x**

### CODE REVIEW

**Comment by linusnorton** [comment]
Why would you do this? Those files are supposed to be committed.

**Comment by victor0801x** [comment]
@linusnorton sorry, i should open a discuss first.
I think lock files are noise for developer, and this library is getting active and populer, and ci build is enable too. 

personally, lock file ignore in repo. but publish to npm.

leave it to @rusher decide ?

**Comment by rusher** [comment]
I've seen npm doc: 

> This file is intended to be committed into source repositories

but since package-lock.json isn't published. I'm still dubious. On the same document:

>  Once it’s present, any future installation will base its work off this file, instead of recalculating dependency versions off package.json.

This package-lock.json file is useful if someone has an issue to reproduced the issue, but i don't see the point of commiting package-lock.json file on github.
I understand that goes in the opposite direction of what npm indicate, but : This only permit to have repeatable build, but do we really want that ? since not published, some might have issues using last dependencies version. Travis/Appveyor not seeing this file will use the last dependencies, validating compatibility.

Glad to have any reaction on that, that's why having an open project is always better, to have a reaction/proposition to improve things. :)

**Comment by linusnorton** [comment]
Well, its your project but normally reproducible builds are definitely a thing you want. You could commit a change which works locally, then fails to build on CI because the packages are different. You might also find that the build works at first, but then the same build fails on a later date. 

As conventional wisdom is to commit the files, it seems that it should be a case of arguing why not to include them. I don't think "they add developer noise" is a strong case for dropping reproducible builds. Just my two cents.

**Comment by victor0801x** [comment]
https://github.com/ethereumjs/merkle-patricia-tree/pull/62#issuecomment-443293041
:+1:

**Comment by linusnorton** [comment]
I get that it's a library and it's not respected downstream, but it seems like you're removing a consistent CI / development experience for no reason. There is no benefit in ignoring these files.

**Pull request merged**
